spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #/<IP>:<PORT>/<DB NAME>?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    url: jdbc:mysql://localhost:3308/news?serverTimezone=Asia/Seoul
    username: root
    password: likelion11
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true


news:
  naver:
    api:
      url: https://openapi.naver.com/v1/search/blog
      client-id: bjy36jO2bPqdpcXVykZI
      client-secret: Y2brS6XLOr