spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true


news:
  naver:
    api:
      url: https://openapi.naver.com/v1/search/news.json
      client-id: bjy36jO2bPqdpcXVykZI
      client-secret: Y2brS6XLOr